### ISSUE TITLE
napi_verify_validate_messages and a panicking crash in Manyverse

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-validate2-rsjs-node#10]
@mycognosist 

I'm actually running ssb-validate2-rsjs with ssb-db2 on my main Manyverse account for the last ~4 days or so (I know, I like to live on the edge), and it's working mostly okay. Sometimes there is a crash, though, so I'm reporting it here.

It doesn't occur too often (which is a good thing) which can make it hard to reliably reproduce (which is a bad thing, makes it difficult to know if a potential fix was effective).

It mentioned `verify_validate_message` and `src/lib.rs` line 237, which seems a lot like it's talking about this line:

https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs-node/blob/2d353613d38537b1d506b16a73112aef07dd010e/src/lib.rs#L237

I stumbled upon it about 3 times. The first time, it didn't give a lot of info, but said I could set `RUST_BACKTRACE=1` to have more info. So I did that and it gave me more info the 2nd time it crashed, but it also said I could get more info by setting `RUST_BACKTRACE=full` which I did, and that one showed on the 3rd run. Below you'll find crash logs for the 3 runs:

## Crash 1

| ![Screenshot_20210710-145459](https://user-images.githubusercontent.com/90512/125343134-653f2480-e35e-11eb-9d38-e0f3a740af83.png) | ![Screenshot_20210710-145554](https://user-images.githubusercontent.com/90512/125343214-78ea8b00-e35e-11eb-9bfb-29669c3edc19.png) |
|-|-|

## Crash 2

| ![Screenshot_20210710-150317](https://user-images.githubusercontent.com/90512/125343399-b0593780-e35e-11eb-8e93-a481d6de2141.png) | ![Screenshot_20210710-150345](https://user-images.githubusercontent.com/90512/125343435-bb13cc80-e35e-11eb-971b-967d05f4cbe6.png) | ![Screenshot_20210710-150418](https://user-images.githubusercontent.com/90512/125343455-c109ad80-e35e-11eb-923a-27b5200cf7c5.png) | ![Screenshot_20210710-150440](https://user-images.githubusercontent.com/90512/125343464-c4049e00-e35e-11eb-8ff5-5c4fa4a7ce3c.png) |
|-|-|-|-|

## Crash 3

| ![Screenshot_20210712-215301](https://user-images.githubusercontent.com/90512/125343593-eb5b6b00-e35e-11eb-9c0d-14e2a08e3f93.png) | ![Screenshot_20210712-215325](https://user-images.githubusercontent.com/90512/125343598-ec8c9800-e35e-11eb-9e60-74907e6a8371.png) | ![Screenshot_20210712-215415](https://user-images.githubusercontent.com/90512/125343600-ed252e80-e35e-11eb-977c-7e7f20c13e49.png) | ![Screenshot_20210712-215446](https://user-images.githubusercontent.com/90512/125343602-edbdc500-e35e-11eb-97b8-c7e1a069f199.png) | ![Screenshot_20210712-215516](https://user-images.githubusercontent.com/90512/125343605-edbdc500-e35e-11eb-8cf5-4e395f8cb488.png) |
|-|-|-|-|-|

**Comment by mycognosist** [comment]
@staltz 

Thanks for the thorough report and logs. There is some definite room for improvement in error handling here, so I'm going to work on that today. We should not be panicking.

The error itself is quite interesting: when batch validation fails, each message is validated individually to be able to catch and return the specific message which failed. In your case, batch validation has failed but then every message has been successfully validated in the one-by-one attempt; thus, we end up with a `None` value after iterating through all messages:

'called `Option::unwrap()` on a `None` value'

Very weird. I'm going to look closely at the code now and see what I can find.

**Comment by staltz** [comment]
Could it be that the error on line 233 is an error unrelated to validation? Like some error about threads or something generic.

**Comment by mycognosist** [comment]
I can't say with complete certainty but it seems very unlikely. There is not much going on in the parallel validation function besides the validation checks themselves. It's mainly just the rayon parallel magic:

```rust
messages.par_iter().enumerate().try_fold(validation function calls happen here).try_reduce();
```

Those rayon functions _are_ fallible but I don't see how they would fail by themselves, if that makes sense. They fail when the underlying function call returns `Option::None` or `Result::Err` (https://docs.rs/rayon/1.5.1/rayon/iter/trait.ParallelIterator.html#method.try_fold).

But I see where you're coming from, in terms of considering an "outside" error source. I have zero experience with multi-threaded applications on mobile so I don't know if there's something inherent in the architecture(s) which can produce these sorts of errors.

**Comment by staltz** [comment]
We could treat the wildcard error even if we don't know what it is or why it could occur. If there is an error from line 233 but no individual invalid message was found, then we can just wrap the error the `Some(err_message)` and return it. This will also help us debug (in runtime, when the error happens again) what the error is, because currently the error we get from 233 is not logged.

**Comment by mycognosist** [comment]
How does this look to you? Nothing here will panic. In the case of an error, we get the underlying error (`e`) plus an explanation of the error (`invalid_msg_str`) which will include the offending message if one is found.

```rust
// attempt batch validation and match on error to find invalid message value
match par_validate_message_value_hash_chain_of_feed(&msgs, previous_msg.as_ref()) {
    Ok(_) => (),
    Err(e) => {
        // validate messages one-by-one, trying to find a single invalid message
        let invalid_msg = &msgs
            .iter()
            .find(|msg| validate_message_value_hash_chain(msg, previous_msg.as_ref()).is_err());
        let invalid_msg_str = match invalid_msg {
            // if an invalid message was found, try to convert the msg bytes to a string slice
            // return the converted string slice or an error if the message was not valid utf-8
            Some(msg) => std::str::from_utf8(msg).unwrap_or(
                "unable to convert invalid message bytes to string slice; not valid utf8",
            ),
            // report if no single invalid message was found
            None => {
                "parallel validation failed but no single message validation error was found"
            }
        };
        let err_msg = format!("found invalid message: {}: {}", e, invalid_msg_str);
        return (Some(err_msg), None);
   }
}
```

**Comment by staltz** [comment]
That's one way that'll work!

**Comment by staltz** [comment]
Well, we can close this fellow. :)
