### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by nichoth** [ssb-ngi-pointer/ssb-validate2-rsjs-node#17]
Following the readme, it says to run

```
nj-cli build --release
```

But then it returns this:
```
ssb-validate2-rsjs-node master % nj-cli build --release                 
error: could not find `Cargo.toml` in `/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node` or any parent directory
```

I notice that when I install this module as a dependency, there is no `Cargo.toml` in the folder with the package, but that file does exist in this git repo. Why is it being ignored?

**Comment by staltz** [comment]
Can you run `npm run build` instead? (I just ran it locally and it built it correctly)

**Comment by nichoth** [comment]
thanks @staltz 

It returns the same error in that case

```
ssb-validate2-rsjs-node master % npm run build

> ssb-validate2-rsjs-node@1.0.3 build
> rm -rf dist && nj-cli build --release

error: could not find `Cargo.toml` in `/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node` or any parent directory
```

**Comment by nichoth** [comment]
__some more clues__
If I clone this repo, it has a `Cargo.toml` of course, but when it is installed as.a dependency, like of `ssb-db2`, then there is not a file `Cargo.toml`

**Comment by staltz** [comment]
Aah, right, that makes all the difference. From the terminal snippets you shared it seemed like you had cloned the repo, especially because you mentioned its readme

**Comment by nichoth** [comment]
Ah ok, sorry. The only thing I can think of is if somehow the file was committed after it was published to `npm`, then the Cargo.toml file was never published to `npm`

**Comment by nichoth** [comment]
__more notes__
If I copy and paste the `Cargo.toml` from this repo, then it outputs this:

```
error: failed to parse manifest at `/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node/Cargo.toml`

Caused by:
  can't find library `ssb-validate2-rsjs-node`, rename file to `src/lib.rs` or specify lib.path
```

**Comment by nichoth** [comment]
It's still a bit of a mystery to me why Cargo.toml is not being published with the package on npm. I even forked and published my own version of this -- https://www.npmjs.com/package/@planetary-ssb/ssb-validate2-rsjs-node , and `Cargo.toml` is in the source and published to npm, but when I install it as a dependency there is no Cargo.toml. 😬

**Comment by staltz** [comment]
Version 1.0.4 is being released now and should fix this for you. The problem was that the npm package does not have Cargo.toml *neither* the Rust source code.

If you run `npm pack --dry-run` you can see that it's missing the Rust source code. I fixed this so that Rust source files and other configs are included in the package.

**Comment by staltz** [comment]
1.0.4 is released. I'll preemptively close this issue, we can re-open if it's still not working

**Comment by nichoth** [comment]
thanks @staltz 
in the `ssb-db2` module, this is the output from `npm test`:

```
ssb-db2 master % npm test

> ssb-db2@2.8.5 test
> tape test/*.js | tap-spec

node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node/dist/index.node, 0x0001): tried: '/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node/dist/index.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/index.node' (no such file), '/usr/lib/index.node' (no such file)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/Users/nick/code/ssb-db2/node_modules/node-bindgen-loader/index.js:27:10)
    at Object.<anonymous> (/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node/index.js:5:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

But if I `cd` into the `node_modules/ssb-validate2-rsjs-node` folder and run `nj-cli build --release`, it seems to be successful

```
   Compiling ssb-validate2-rsjs-node v1.0.3 (/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node)
    Finished release [optimized] target(s) in 1.95s
```

So it looks like this part at least is ok…
